# Generated by Django 5.0.6 on 2024-09-18 06:13

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=150, unique=True)),
                ('brand_email', models.EmailField(max_length=254, unique=True)),
                ('brand_logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=60, scale=None, size=[1920, 1080], upload_to='Designers')),
                ('brand_bio', models.TextField(default='description')),
                ('brand_location', models.CharField(default='here', max_length=150)),
                ('brand_phone', models.CharField(max_length=14)),
                ('google_map_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.CharField(choices=[('NO', 'No'), ('YES', 'YES')], default='NO', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Designer',
                'verbose_name_plural': 'Designers',
            },
        ),
    ]
