# Generated by Django 5.0.6 on 2024-10-21 18:32

import creators.models
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='brand_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=60, scale=None, size=[100, 150], upload_to=creators.models.brand_path),
        ),
        migrations.AlterField(
            model_name='style',
            name='asking_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
        ),
        migrations.AlterField(
            model_name='style',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=60, scale=None, size=[1080, 1080], upload_to=creators.models.style_path),
        ),
        migrations.AlterField(
            model_name='styleimage',
            name='image',
            field=models.ImageField(upload_to='Stylesimages/'),
        ),
    ]
