# Generated by Django 5.0.6 on 2024-09-29 14:51

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='brand_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=60, scale=0.5, size=[1080, 1080], upload_to='Designers'),
        ),
    ]
