# Generated by Django 5.0.6 on 2024-09-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
