# Generated by Django 5.0.6 on 2024-09-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_user_wishlist_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wishlist_items',
            new_name='wishlist_count',
        ),
    ]
