# Generated by Django 5.0.6 on 2024-09-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_rename_wishlist_items_user_wishlist_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='designer',
            name='phone_no',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
