# Generated by Django 5.0.6 on 2024-08-23 13:51

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_alter_designer_brand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='location',
            field=models.CharField(default='here', max_length=150),
        ),
        migrations.AlterField(
            model_name='designer',
            name='brand_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=60, scale=None, size=[1920, 1080], upload_to='Designers/<function user_dir_path at 0x78b7f5556840>'),
        ),
    ]
