# Generated by Django 5.0.6 on 2024-09-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_designer_description_designer_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address2',
        ),
    ]
