# Generated by Django 5.0.6 on 2024-08-23 14:33

import datetime
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_designer_location_alter_designer_brand_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('thumbnail', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=60, scale=None, size=[1920, 1080], upload_to='Categories')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='designer',
            options={'verbose_name': 'Designer', 'verbose_name_plural': 'Designers'},
        ),
        migrations.AddField(
            model_name='designer',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='google_map',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designer',
            name='other_online_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='designer',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='designer',
            name='brand_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=60, scale=None, size=[1920, 1080], upload_to='Designers/<function user_dir_path at 0x7429253568e0>'),
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('images', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=60, scale=None, size=[1920, 1080], upload_to='Styles/<function user_dir_path at 0x7429253568e0>')),
                ('can_request', models.BooleanField(default=False)),
                ('asking_price', models.DecimalField(decimal_places=2, default=0.99, max_digits=9999999999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(verbose_name=datetime.datetime(2024, 8, 23, 14, 33, 47, 999444, tzinfo=datetime.timezone.utc))),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.category')),
                ('designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.designer')),
            ],
            options={
                'verbose_name': 'Style',
                'verbose_name_plural': 'Styles',
            },
        ),
    ]
