# Generated by Django 5.0.6 on 2024-09-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_remove_shippingaddress_address2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1',
            new_name='address',
        ),
    ]
