# Generated by Django 5.0.6 on 2024-09-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_rename_address1_shippingaddress_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designer',
            old_name='google_map',
            new_name='google_map_url',
        ),
        migrations.RemoveField(
            model_name='designer',
            name='other_online_link',
        ),
    ]
