# Generated by Django 5.0.6 on 2024-09-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_rename_google_map_designer_google_map_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designer',
            old_name='description',
            new_name='brand_bio',
        ),
        migrations.RenameField(
            model_name='designer',
            old_name='location',
            new_name='brand_location',
        ),
        migrations.RenameField(
            model_name='designer',
            old_name='phone_no',
            new_name='brand_phone',
        ),
    ]
