version: '3.8'

services:
  django:
    build: .
    env_file:
      - .env
    container_name: tailorapp
    ports:
      - "8000:8000"
    # networks:
    #   - external_network
    command: python manage.py runserver 0.0.0.0:8000

# networks:
#   external_network:
#     external: true