version: '3.8'

services:
  django:
    build: .
    env_file:
      - .env
    container_name: tailorapp
    ports:
      - "8000:8000"
    networks:
       - external_network
    
    # development
    command: python manage.py runserver 0.0.0.0:8000
      # production
    #ommand: gunicorn TailorConnect.wsgi:application --bind 0.0.0.0:8000

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A TailorConnect worker -l info
    env_file:
      - .env
    networks:
      - external_network
    volumes:
      - .:/app

networks:
  external_network:
     external: true
