version: '3.8'

services:
  tailorapp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: tailorapp
    ports:
      - "8000:8000"
    # development
    command: python manage.py runserver 0.0.0.0:8000
      # production
    #ommand: gunicorn TailorConnect.wsgi:application --bind 0.0.0.0:8000

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    command: celery -A TailorConnect worker -l info
    env_file:
      - .env
    volumes:
      - .:/app

#   redis:
#     image: redis:7.0-alpine
#     ports:
#       - "6389:6389"
#     networks:
#       - external_network


# networks:
#   external_network:
#     #  external: true
