# Generated by Django 5.0.6 on 2024-10-03 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authUser', '0001_initial'),
        ('creators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Successful', 'Successful'), ('Cancelled', 'Cancelled')], default='Processing', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9999999999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authUser.measurement')),
                ('shipp_addr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authUser.shippingaddress')),
                ('style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='creators.style')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=999999999999)),
                ('ref', models.CharField(max_length=300)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.order')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
