# Generated by Django 5.0.6 on 2024-10-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_donations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Successful', 'Successful'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='Processing', max_length=12),
        ),
    ]
