# Generated by Django 5.1.2 on 2024-12-13 18:33

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_order_refrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='refrence',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, unique=True),
        ),
    ]
