# Generated by Django 5.1.2 on 2024-12-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_order_refrence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='refrence',
            new_name='payment_refrence',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ref',
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_refrence',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_refrence',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_refrence',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
