# Generated by Django 5.1.2 on 2024-12-14 04:14

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_refrence_order_payment_refrence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='ref',
        ),
        migrations.AddField(
            model_name='donations',
            name='payment_refrence',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='donations',
            name='transaction_refrence',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
