# Generated by Django 5.1.2 on 2024-12-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_donations_ref_donations_payment_refrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
