# Generated by Django 5.1.2 on 2024-12-14 06:05

import payment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_donations_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='payment_refrence',
            field=models.CharField(default=payment.models.short_uuid7, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_refrence',
            field=models.CharField(default=payment.models.short_uuid7, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_refrence',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
