{
    'Abia': ['Umuahia North', 'Umuahia South', 'Ikwuano', 'Obioma Ngwa North'],
 'Adamawa': ['Yola North', 'Yola South', 'Ganye', 'Jada'],
 'Akwa Ibom': ['Uyo', 'Ikot Ekpene', 'Eket', 'Oron'],
 'Anambra': ['Awka South', 'Awka North', 'Onitsha North', 'Onitsha South'],
 'Bauchi': ['Bauchi', 'Dass', 'Bogoro', 'Tafawa Balewa'],
 'Bayelsa': ['Yenagoa', 'Sagbama', 'Southern Ijaw', 'Kolokuma/Opokuma'],
 'Benue': ['Makurdi', 'Gboko', 'Otukpo', 'Katsina-Ala'],
 'Borno': ['Maiduguri', 'Bama', 'Gwoza', 'Kukawa'],
 'Cross River': ['Calabar South','Calabar Municipality','Odukpani','Akpabuyo'],
 'Delta': ['Warri South', 'Warri North', 'Udu', 'Okpe'],
 'Ebonyi': ['Abakaliki', 'Afikpo North', 'Afikpo South', 'Ebonyi'],
 'Edo': ['Benin City', 'Egor', 'Oredo', 'Ikpoba-Okha'],
 'Ekiti': ['Ado Ekiti', 'Ikere Ekiti', 'Ido Osi', 'Ilejemeje'],
 'Enugu': ['Enugu East', 'Enugu North', 'Enugu South', 'Igbo Etiti'],
 'Gombe': ['Gombe', 'Akko', 'Balanga', 'Dukku'],
 'Imo': ['Owerri North', 'Owerri South', 'Owerri Municipal', 'Orlu'],
 'Jigawa': ['Dutse', 'Ringim', 'Malam Madori', 'Buji'],
 'Kaduna': ['Kaduna North', 'Kaduna South', 'Igabi', 'Zaria'],
 'Kano': ['Kano Municipal', 'Dala', 'Kumbotso', 'Tarauni'],
 'Kastina': ['Katsina Municipal', 'Daura', 'Funtua', 'Kankara'],
 'Kebbi': ['Birnin Kebbi', 'Bunza', 'Gwandu', 'Jega'],
 'Kogi': ['Lokoja', 'Kogi', 'Ijumu', 'Idah'],
 'Kwara': ['Ilorin South', 'Ilorin West', 'Ilorin East', 'Asa'],
 'Lagos': ['Ikeja', 'Surulere', 'Kosofe', 'Mushin'],
 'Nasarawa': ['Lafia', 'Nasarawa', 'Keffi', 'Karu'],
 'Niger': ['Minna', 'Bosso', 'Chanchaga', 'Agaie'],
 'Ogun': ['Abeokuta North', 'Abeokuta South', 'Ogun Waterside', 'Remo North'],
 'Ondo': ['Akure North', 'Akure South', 'Owo', 'Ifedore'],
 'Osun': ['Osogbo', 'Ado-Ekiti West', 'Ilesa East', 'Ilesa West'],
 'Oyobo': ['Oyobo', 'Ikeja', 'Surulere', 'Kosofe'],
 'Plateau': ['Jos North', 'Jos South', 'Barkin Ladi', 'Bassa'],
 'Rivers': ['Port Harcourt', 'Obio/Akpor', 'Ikwerre', 'Oyigbo'],
 'Sokoto': ['Sokoto South', 'Sokoto North', 'Wurno', 'Gada'],
 'Taraba': ['Jalingo', 'Wukari', 'Gashaka, Kurmi', 'Sardauna'],
 'Yobe': ['Damaturu', 'Buni Yadi', 'Fika', 'Guzamala'],
 'Zamfara': ['Gusau', 'Maradun', 'Kaura Namoda', 'Shinkafi']
 }