# Generated by Django 5.1.2 on 2024-10-25 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authUser', '0001_initial'),
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='members',
            field=models.ManyToManyField(to='creators.style'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
