# Generated by Django 5.0.6 on 2024-09-30 06:35

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=60, scale=0.5, size=[100, 150], upload_to='Users'),
        ),
    ]
