# Generated by Django 5.0.6 on 2024-08-23 13:51

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUserApp', '0003_alter_user_avatar_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=60, scale=None, size=[1920, 1080], upload_to='Users/<function user_dir_path at 0x78b7f5c9bba0>'),
        ),
    ]
