# Generated by Django 5.0.6 on 2024-09-30 18:23

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='images',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=60, scale=0.5, size=[1080, 1080], upload_to='Styles'),
        ),
    ]
