# Generated by Django 5.0.6 on 2024-09-29 14:19

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='images',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=60, scale=None, size=[1080, 1080], upload_to='Styles'),
        ),
    ]
