# Generated by Django 5.0.6 on 2024-09-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_alter_style_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='style',
            old_name='images',
            new_name='thumbnail',
        ),
    ]
