# Generated by Django 5.0.6 on 2024-09-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_alter_style_can_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='asking_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=9999999999),
        ),
    ]
